### ISSUE TITLE
v3.0.0 release缺少aspxEval_Cookie.type导致"... hasn't been registered"错误

### ISSUE THREAD

**Issue by lynnux** [keepwn/Altman#17]
v3.0.0 release缺少aspxEval_Cookie.type导致"... hasn't been registered"错误

调试代码发现Altman.Webshell.InitWorker里的RegisterCustomShellType中段throw，导致后面所有func都没有注册，从而引发hasn't been registered错误。而引发throw的是aspxEval_Cookie这个type没找到，我在CustomType看了下确实没有这个aspxEval_Cookie.type这个文件，于是复制了一份aspEval_Cookie.type更名为aspxEval_Cookie.type，并将里面的name改了。重新运行程序，功能正常！
由于对aspx不熟悉，暂时也用不到aspx_cookie，也只能这样了，望官方尽快补上丢失的文件，谢谢！

**Comment by lynnux** [comment]
不好意思，打扰了，貌似是我的机子有问题，那个文件莫名其妙不见了

**Comment by keepwn** [comment]
没事的，遇到任何问题都可以提交到Issues:)
