### ISSUE TITLE
问题/建议：文件管理器若干问题

### ISSUE THREAD

**Issue by aaaaaaaannn** [keepwn/Altman#22]
问题一：目录树shell所在路径始终展开

比如你的shell路径是在d:\www\
第一次打开文件管理器,目录树就会自动定位到d:\www\
此时你在目录树将所在shell目录收起（也就是d:\www\）
再访问另外一个路径，比如是d:\soft\.
d:\soft展开后，shell所在路径同时（d:\www\）也被展开了（本来是收起的）.
就是说访问任何一个父级路径，shell所在路径始终被展开。这样对于目录多的情况，浏览起来非常吃力。

问题二：路径输入框对回车键无效
比如我在路径输入栏里填写一个自定义路径要按Dir键才有回显,而回车键却不行。有点不灵活～

问题三：对于linux来说路径输入框里总是多了一个/
//var/log
（路径前面Altman多添加了一个/）

问题四：通过目录树选择的路径和dir按钮进入的路径产生冲突
比如在目录树中进入了A路径，这时你突发奇想用路径输入栏进入了一个B路径（dir按钮进入）。
这时你在文件列表里右键“刷新”却显示的是A路径的文件列表。不同的路径，地址变量应该是绝对的，在一定程度上没有共通，才导致的。 ( ͡° ͜ʖ ͡°) 　

建议一：上传/下载可以加上进度条就好了
   对于我们来说进度条太重要了,多一个进度条可以让我们方便了解状态。

建议二：打开文件类型默认是脚本文件，可以取消吗？
   此处感觉有一点多余了，每次上传不同类型文件都要重新作一番调整。好没有爱～ヽ(.◕ฺˇд ˇ◕ฺ;)ﾉ

建议三：进入目录需要双击图标才行～
   对于一般用户可能一下子不能适应，现在双击文件名就会进入命名状态，我感觉大可不必，可以肯定大部分用户还是喜欢通过右键菜单来重命名。

建议四：右键编辑键和删除键挨的也太近了
 鄙人长年有手抖的毛病，加上Altman先天性，已经错干好多文件了。希望删除可以靠后一点。另外不可逆操作最好加上确认框。

**Comment by keepwn** [comment]
一口气提了这么多的问题，泥真是垢了:)
- 问题一~ 四，直接解决没商量。
- 建议一：进度条待定，一直没找到好的展示方式
- 建议二：已解决
- 建议三：使用gtk版本会出现这种情况，目前不好解决。（鼠标悬停编辑功能和右键编辑功能，由于系统限制，只能同时开启或关闭）
- 建议四：已解决

**Comment by aaaaaaaannn** [comment]
谢谢作者的耕耘。相信以后会有更多人关注！
