### ISSUE TITLE
[ShellCmder]: 命令终端问题

### ISSUE THREAD

**Issue by aaaaaaaannn** [keepwn/Altman#30]
重现：
测试的是gtk版本,先执行一条命令,返回命令结果后按Up键翻找历史命令，第一次没问题，多按一次命令终端界面就会被重新清屏，内容显示混乱也见不到命令交互行。按回车键就会恢复正常。输入法调成IBUS拼音模式,奇怪的是还能在命令行界面随意编辑(在IBUS输入法下按shift 转为英文更明显)，命令交互处要输入命令，自己要将光标点过去才行，不然无法定位到这里。我将IBUS挑换为系统默认英文输入模式就一切正常了。

使用的过程中经常出现，这里想单独测试一下还找不出来，没感觉是IBUS出的问题，无意中将输入法调为IBUS问题就重现了，可能是IBUS问题。这个问题比较隐蔽，希望作者可以解决。

**Comment by keepwn** [comment]
不是IBUS输入法的问题，是之前更新Eto.dll时导致的一个Bug。
